#
# Outgoing email settings
# To enable ssl connection, port must be 587 or 465.
# Some SMTP auth requires a domain, which does not have
# to be a real domain, but it must exist.
#

production:
#  delivery_method: :sendmail
  delivery_method: :smtp
  smtp_settings:
    domain: localhost
    address: brueckenschlaeger.de
    port: 587
    authentication: :plain
    user_name: "andi@brueckenschlaeger.de"
    password: "UrinHopl!"


development:
#  delivery_method: :sendmail
  delivery_method: :smtp
  smtp_settings:
    domain: brueckenschlaeger.de
    address: mail.brueckenschlaeger.de
    port: 587
    authentication: :plain
    user_name: "andi@brueckenschlaeger.de"
    password: "UrinHopl!"

