default:
  name: crabgrass
  domain: localhost
  email_sender: 'crabgrass-system@localhost'
  secret: 'd24833cab5fafcd17f2c555f7663c0524a938e5ed6df2af8bf134d3959fc8ac3214fa8c7'
  pagination_size: 29
  default_language:
  - english
  available_page_types:
  - Message
  - Discussion
  - Wiki
  - Article
  - RateMany
  - RankedVote
  - TaskList
  - Asset
  - Gallery
  - ExternalVideo

